The task of the tenth lesson
Marukaska/hinknetica-ror-second-step pull request #9
Opened 2024-06-04 13:15 UTC by Marukaska

The task of the tenth lesson

2024-06-04 16:59 UTC, BubuntuClu requested changes

2024-06-04 16:59 UTC, BubuntuClu commented on test-guru/app/controllers/sessions_controller.rb
> +      redirect_to(session[:forwarding_url] || root_path)
> С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально

так, вижу использование сессии, но не вижу где ты ее сохраняешь. и то что это не кука, тоже вопросик

2024-06-04 16:59 UTC, BubuntuClu commented on test-guru/app/helpers/flash_helper.rb
> +    nil
чтобы не было этого костыля вместо `each` попробуй `map` использовать

2024-06-04 16:59 UTC, BubuntuClu commented on test-guru/app/views/sessions/_form.html.erb
> +    <% if flash[:alert] %>
тут тоже можно твой хэлпер с нотификациями использовать

2024-06-04 16:59 UTC, BubuntuClu commented on test-guru/config/routes.rb
> +  get 'users/new'
это дубли роутов, которые ты ниже добавил

2024-06-04 16:59 UTC, BubuntuClu commented on test-guru/app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2024-06-05 10:39 UTC, Marukaska commented on test-guru/config/routes.rb
> +  get 'users/new'
Видимо это автоматически созданные роуты при создании контролера, я не заметил что они автоматом прописываются

2024-06-05 17:51 UTC, BubuntuClu commented on test-guru/app/controllers/sessions_controller.rb
> +      redirect_to(cookies.delete(:before_url)|| root_path)
ты используешь куку, чтобы сделать туда редирект. но чтобы его сделать, тебе ведь надо сохранить в эту куку url куда рекдирект сделать. этот пункт задания ты не сделал. в текущей реализации тут всегда будет пусто и будет происходить редирект на рут

2024-06-05 17:51 UTC, BubuntuClu commented on test-guru/app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
колбэк прописан в родительском контроллере

2024-06-10 09:56 UTC, merged